all: compile

compile:
	clang++ -Wall -Wextra -Werror megaphone.cpp -o megaphone

test1:
	./megaphone "shhhhh... I think the students are asleep..."

test2:
	./megaphone Damnit " ! " "Sorry students, I thought this thing was off."